name: build-analyze-scan

on:
  push:
    branches:
      - main

jobs:
  build-analyze-scan:
    name: Build, Analyze, and Scan
    runs-on: self-hosted
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build code and analyze with SonarQube
        uses: actions/checkout@master # Replace with the correct action for SonarQube
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Install dependencies
        run: npm install

      - name: Trivy vulnerability scan
        run: trivy fs . --format json -o trivy-report.json

      - name: Docker build and push
        run: |
          echo  ${{ secrets.DOCKERHUB_TOKEN }}$DOCKERHUB_TOKEN | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker build -t jackquick/zomato .
          docker tag jackquick/zomato:latest jackquick/zomato:latest
          docker push jackquick/zomato:latest
        env:
          DOCKER_CLI_ACL: 1

  deploy:
    name: Deploy app to Docker
    needs: build-analyze-scan
    runs-on: self-hosted
    steps:
      - name: Pull Docker image
        run: docker pull jackquick/zomato:latest

      - name: Image scan with Trivy
        run: trivy image jackquick/zomato:latest > image-trivy-scan.txt

      - name: Run Docker container
        run: docker run -itd -p 3000:3000 --name zomato jackquick/zomato:latest