name: build-analyze-scan

on:
  push:
    branches:
      - main

jobs:
  build-analyze-scan:
    name: Build, Analyze, and Scan
    runs-on: self-hosted
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build code
        run: npm install

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v3
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Add your SonarQube token as a secret
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}  # Add your SonarQube server URL as a secret

      - name: Trivy vulnerability scan
        run: trivy fs . --format json -o trivy-report.json

      - name: Docker build and push
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker build -t jackquick/zomato .
          docker push jackquick/zomato:latest

  deploy:
    name: Deploy app to Docker
    needs: build-analyze-scan
    runs-on: self-hosted
    steps:
      - name: Pull Docker image
        run: docker pull jackquick/zomato:latest

      - name: Image scan with Trivy
        run: trivy image jackquick/zomato:latest > image-trivy-scan.txt

      - name: Run Docker container
        run: docker run -itd -p 3000:3000 --name zomato jackquick/zomato:latest
